library(TCC)
set.seed(1234567)
tcc <- generateSimulationData(Ngene = 100, PDEG = 0.2, DEG.assign = c(0.9, 0.1))
tcc <- calcNormFactors(tcc)
tcc <- estimateDE(tcc, test.method = "bayseq", FDR = 0.1, samplesize = 1000)
result <- getResult(tcc, sort = TRUE)
print(head(result))
table(tcc$estimatedDEG) 
png("plot4b.png", 600, 500)
plot(tcc)
dev.off()
