library(TCC)
set.seed(1234567)
tcc <- generateSimulationData(Ngene = 100, PDEG = 0.2, DEG.assign = c(0.9, 0.1))
cat("simulation data generated \n")
tcc <- calcNormFactors(tcc, norm.method = "tmm", test.method = "edger")
cat("tcc$norm.factors: ")
cat(tcc$norm.factors)
cat("\n")
cat("tcc$stat$execution.time: ")
cat(tcc$stat$execution.time)
cat("\n")
