if (Sys.getenv("TCC_REAL_TEST") != ""){
  library(TCC)
  data(hypoData)
  group <- c(3, 3)
  tcc <- new("TCC", hypoData, c(3,3))
  cat("tcc$count: ")
  cat(dim(tcc$count))
  cat("\n")
  tccf <- filterUnexpressedGenes(tcc)
  cat("dim(tcc$count): ")
  cat(dim(tccf$count))
  cat("\n")
  cat("dim(hypoData): ")
  cat(dim(hypoData))
  cat("\n")
  cat("dim(hypoData[as.logical(rowSums(hypoData)>0),]): ")
  cat(dim(hypoData[as.logical(rowSums(hypoData) > 0),]))
  cat("\n")
}
