library(TCC)
data(hypoData)
group <- c(1, 1, 1, 2, 2, 2)
tcc <- new("TCC", hypoData, group)
cat("tcc$count: ")
cat(dim(tcc$count))
cat("\n")
tccf <- filterLowCountGenes(tcc)
cat("dim(tcc$count): ")
cat(dim(tccf$count))
cat("\n")
cat("dim(hypoData): ")
cat(dim(hypoData))
cat("\n")
cat("dim(hypoData[as.logical(rowSums(hypoData)>0),]): ")
cat(dim(hypoData[as.logical(rowSums(hypoData) > 0),]))
cat("\n")
