library(TCC)
  set.seed(1234567)
  tcc <- generateSimulationData(Ngene = 1000, PDEG = 0.3,
                         DEG.assign = c(0.6, 0.2, 0.2),
                         DEG.foldchange = list(3, 10, 6),
                         replicates = c(2, 4, 3))
  cat("dim(tcc$count): ")
  cat(dim(tcc$count))
  cat("\n")
  cat("tcc$group$group: ")
  cat(tcc$group$group)
  cat("\n")
  cat("tcc$count: ")
  cat("\n")
  print(head(tcc$count))
  png("plot5-3-1.png", 500, 500)
  plotFCPseudocolor(tcc)
  dev.off()
  png("plot5-3-2.png", 600, 600)
  plot(tcc)
  dev.off()
