library(TCC)
data(hypoData)
set.seed(27253047)
tcc <- simulateReadCounts(Ngene = 100, PDEG = 0.2, DEG.assign = c(0.9, 0.1))
#  group <- c(3, 3)
#  tcc <- new("TCC", hypoData, c(3,3))
show(tcc)
sub_tcc <- subset(tcc,1:10*10)
show(sub_tcc)
sub2_tcc <- tcc[1:10*10-1]
show(sub2_tcc)
tcc$calcNormFactors(norm.method = "tmm", test.method = "bayseq")
tcc$estimateDE(test.method = "edger", FDR = 0.1)

sub_tcc <- subset(tcc,1:10*10)
show(sub_tcc)

show(tcc[c("gene_13", "gene_17", "gene_23")])
result <- getResult(sub_tcc, sort = TRUE)
print(head(result))
